# Generated by Django 3.0.7 on 2020-06-12 20:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('vacancies', '0004_auto_20200612_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='written_username',
            field=models.CharField(max_length=64, verbose_name='Вас зовут'),
        ),
    ]
