# Generated by Django 3.0.7 on 2020-06-12 20:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('vacancies', '0005_auto_20200612_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='written_cover_letter',
            field=models.TextField(verbose_name='Сопроводительное письмо'),
        ),
        migrations.AlterField(
            model_name='application',
            name='written_phone',
            field=models.CharField(max_length=64, verbose_name='Ваш телефон'),
        ),
    ]
