# Generated by Django 3.0.7 on 2020-06-14 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('vacancies', '0006_auto_20200612_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='skills',
            field=models.TextField(),
        ),
    ]
